import type { Metadata } from "next";
import "../globals.css";
import { Sponsors } from "@/components/Sponsors";
import { Header } from "@/components/Header";
import Image from "next/image";
import { Intro } from "@/components/Intro";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex items-center p-2 lg:p-0 justify-center min-h-[100vh] overflow-x-hidden bg-[#973f0f]`}
      >
        <Intro />
        <div className="bg absolute top-0 left-0 w-full h-full z-0 opacity-[30%]">
          <Image
            src={"/background.png"}
            alt="background"
            fill
            className="w-full h-full object-cover"
          />
        </div>
        <div className="page flex flex-col lg:flex-row z-10 p-4">
          <div className="content relative p-4 bg-white rounded-tl-2xl rounded-bl-2xl max-w-[700px] w-auto">
            <Image
              src={"/content-background.png"}
              fill
              alt="background"
              className="z-0 opacity-50 object-cover"
              draggable={false}
            />
            <Header />
            {children}
          </div>
          <Sponsors />
        </div>
      </body>
    </html>
  );
}
