import type { Metadata } from "next";
import "../globals.css";
import { Header } from "./dashboard/components/Header";
import { Sidebar } from "./dashboard/components/Sidebar";
import { QueryProvider } from "@/providers/QueryClientProvider";
import { Toaster } from "sonner";
import DashboardPageMetaTags from "@/components/DashboardMetaTags";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DashboardPageMetaTags />
      <body className={`antialiased bg-[#f5eeeb]`}>
        <Toaster />
        <QueryProvider>
          <div className="page dashboard-layout">
            <Sidebar />
            <Header />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
